freebsd_instance:
  cpu: 4
  memory: "4"

env:
  HOME: "/root"
  PATH: "/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/root/bin"
  USER: "root"

install_template: &INSTALL_PLUGIN
  install_script: .cirrus/install_script.sh


esphome_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('esphome.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "esphome.json"

gogs_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('gogs.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "gogs.json"

homeassistant_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('homeassistant.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "homeassistant.json"

mosquitto_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('mosquitto.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "mosquitto.json"

node-red_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('node-red.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "node-red.json"

tasmoadmin_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('tasmoadmin.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "tasmoadmin.json"

zwavejs2mqtt_task:
  <<: *INSTALL_PLUGIN
  only_if: "changesInclude('zwavejs2mqtt.json', '.cirrus/install_script.sh')"
  matrix:
    - freebsd_instance:
        image_family: freebsd-12-2
  env:
    PLUGIN_FILE: "zwavejs2mqtt.json"
